/**:
  ros__parameters:
    diagnostic_updater:
      hardware_id: 'none'
    filter1:
      name: base_polygon_filter
      type: laser_filters/LaserScanPolygonFilter
      params:
        polygon_frame: base_link
        polygon: '[[0.1, -0.3], [0.1, 0.3], [-0.5, 0.3], [-0.5, -0.3]]'
        invert: false
    qos_overrides:
      /scan:
        subscription:
          reliability: best_effort
          history: keep_last
          depth: 10
