/**:
  ros__parameters:
    filter1:
      name: base_polygon_filter
      type: laser_filters/LaserScanPolygonFilter
      params:
        polygon_frame: base_link
        polygon: '[[0.28, -0.22], [0.28, 0.22], [-0.36, 0.22], [-0.36, -0.22]]'
        invert: false
